name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/smartarters:latest
        docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/smartarters:${{ github.event.head_commit.message }}

    - name: Push the Docker image
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/smartarters:latest
        docker push ghcr.io/${{ github.repository_owner }}/smartarters:${{ github.event.head_commit.message }}
